/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toolVendor;

public class SampleApp {   

    public static void main(String[] args) {
        System.out.println(new SampleApp().getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
